export const puzzles = {
	'02.18.2024': [
		['cat', 'tac'],
		['smile', 'imsle'],
		['window', 'wodwin'],
		['computer', 'mcuprote'],
		['building', 'nibudlig'],
		['temperature', 'rerueatmpte'],
	],
	'02.19.2024': [
		['pen', 'npe'],
		['sail', 'lais'],
		['dress', 'ssedr'],
		['travel', 'levart'],
		['mountain', 'ntainmou'],
		['opportunity', 'ytinuoptorto'],
	],
	'02.20.2024': [
		['cup', 'puc'],
		['laugh', 'ghual'],
		['flower', 'reolfw'],
		['rainbow', 'wonibar'],
		['adventure', 'retnudeva'],
		['imagination', 'natiomigani'],
	],
	'02.21.2024': [
		['pot', 'top'],
		['smile', 'emils'],
		['garden', 'nerdga'],
		['telephone', 'onehpetloet'],
		['discovery', 'yrevocsid'],
		['inspiration', 'noitarpisni'],
	],
	'02.22.2024': [
		['box', 'box'],
		['dance', 'enced'],
		['kitchen', 'nehctik'],
		['microphone', 'enohpcorim'],
		['confidence', 'encidnecof'],
		['determination', 'noitamniretned'],
	],
	'02.23.2024': [
		['car', 'rac'],
		['jump', 'pmju'],
		['library', 'yrabril'],
		['telescope', 'esopletco'],
		['satisfaction', 'noitasfactions'],
		['perspectives', 'sectivperpse'],
	],
	'02.24.2024': [
		['dog', 'odg'],
		['sing', 'gnis'],
		['bathroom', 'moortbah'],
		['telescope', 'esopletco'],
		['transformation', 'namtrofniamrot'],
		['collaboration', 'noitaroballco'],
	],
	'02.25.2024': [
		['sun', 'nus'],
		['read', 'daer'],
		['bedroom', 'mredoob'],
		['microscope', 'emosccpoere'],
		['appreciation', 'noitaicireppa'],
		['encouragement', 'netamnegracoren'],
	],
	'02.26.2024': [
		['bed', 'deb'],
		['write', 'ewrit'],
		['living room', 'moor gnivil'],
		['transportation', ' tatnriropnosact'],
		['celebration', 'noitabralec'],
		['perseverance', 'ecnevresenrep'],
	],
	'02.27.2024': [
		['cat', 'tac'],
		['play', 'yalp'],
		['playground', 'ydnuorglap'],
		['opportunity', 'ytinuoptorto'],
		['achievement', 'vemnetaihcea'],
		['collaboration', 'noitaroballco'],
	]
};
