name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set current date as env variable'
        run: |
          echo "builddate=$(date +'%Y-%m-%d:%T')" >> $GITHUB_OUTPUT
        id: version
      - name: Clear lockfile
        run: rm -rf package-lock.json
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Install Deps
        run: npm install
      - name: Run Vitest Tests
        run: npm run test:unit
      - name: Install Playwright
        run: npx playwright install chromium
      - name: Build App
        run: npm run build
      - name: Run Playwright Tests
        run: npm run test
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
